import { useEffect, useState } from "react";
import { createAmkrPool, createAmkrProvider, createAmkrProviderKey, deleteAmkrProvider, getAmkrProviders, type AmkrProvider, type AmkrProvidersResponse } from "../../api/amkr";

const csv = (value: string) => value.split(",").map((item) => item.trim()).filter(Boolean);

function ProviderCard({ provider, revision, refresh }: { provider: AmkrProvider; revision: string; refresh: () => Promise<void> }) {
  const [keyName, setKeyName] = useState(""); const [keyValue, setKeyValue] = useState(""); const [allowVisitor, setAllowVisitor] = useState(false);
  const [poolName, setPoolName] = useState(""); const [poolKeys, setPoolKeys] = useState(""); const [poolModels, setPoolModels] = useState(""); const [error, setError] = useState<string | null>(null);
  const mutate = async (operation: () => Promise<unknown>) => { setError(null); try { await operation(); await refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } };
  return <article className="provider-item"><header><div><h3>{provider.id}</h3><p>{provider.base_url}</p></div><button className="danger-button" type="button" onClick={() => void mutate(() => deleteAmkrProvider(revision, provider.id))}>删除</button></header><div className="provider-details">
    <section aria-label={`${provider.id} 的 Key`}><h4>Key</h4>{provider.keys.length ? <ul>{provider.keys.map((key) => <li key={key.name}><span>{key.name}</span><code>{key.api_key_fingerprint}</code><span className={key.enabled ? "status-good" : "status-muted"}>{key.enabled ? "已启用" : "已停用"}</span></li>)}</ul> : <p>尚无 Key。</p>}<form className="inline-form" onSubmit={(event) => { event.preventDefault(); void mutate(async () => { await createAmkrProviderKey(revision, provider.id, keyName, keyValue, allowVisitor); setKeyName(""); setKeyValue(""); setAllowVisitor(false); }); }}><label>名称<input required value={keyName} onChange={(event) => setKeyName(event.target.value)} /></label><label>API Key<input required type="password" value={keyValue} onChange={(event) => setKeyValue(event.target.value)} /></label><label className="checkbox-label"><input checked={allowVisitor} type="checkbox" onChange={(event) => setAllowVisitor(event.target.checked)} />访客访问</label><button type="submit">添加 Key</button></form></section>
    <section aria-label={`${provider.id} 的模型池`}><h4>模型池</h4>{provider.pools.length ? <ul>{provider.pools.map((pool) => <li key={pool.name}><span>{pool.name}</span><span>{pool.models.join(", ") || "未绑定模型"}</span></li>)}</ul> : <p>尚无模型池。</p>}<form className="inline-form" onSubmit={(event) => { event.preventDefault(); void mutate(async () => { await createAmkrPool(revision, provider.id, poolName, csv(poolKeys), csv(poolModels)); setPoolName(""); setPoolKeys(""); setPoolModels(""); }); }}><label>名称<input required value={poolName} onChange={(event) => setPoolName(event.target.value)} /></label><label>Key<input value={poolKeys} onChange={(event) => setPoolKeys(event.target.value)} placeholder="逗号分隔" /></label><label>模型<input value={poolModels} onChange={(event) => setPoolModels(event.target.value)} placeholder="逗号分隔" /></label><button type="submit">添加模型池</button></form></section>
  </div>{error ? <p className="service-action-error">操作失败: {error}</p> : null}</article>;
}

export function ProvidersPage() {
  const [data, setData] = useState<AmkrProvidersResponse | null>(null); const [id, setId] = useState(""); const [baseUrl, setBaseUrl] = useState(""); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  const refresh = async () => { setLoading(true); try { setData(await getAmkrProviders()); setError(null); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setLoading(false); } };
  useEffect(() => { void refresh(); }, []);
  return <section className="providers-page" aria-labelledby="providers-heading"><header className="page-header"><div><h2 id="providers-heading">供应商</h2><p>管理本机 AMKR 的上游连接、Key 与模型池。</p></div>{data ? <span className="config-revision">版本 {data.config_revision.slice(0, 12)}</span> : null}</header><form className="provider-create" onSubmit={(event) => { event.preventDefault(); if (!data) return; void (async () => { try { await createAmkrProvider(data.config_revision, id, baseUrl); setId(""); setBaseUrl(""); await refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } })(); }}><label>名称<input required value={id} onChange={(event) => setId(event.target.value)} /></label><label>地址<input required type="url" value={baseUrl} onChange={(event) => setBaseUrl(event.target.value)} /></label><button type="submit" disabled={!data || loading}>添加供应商</button></form>{loading ? <p className="empty-state">正在读取供应商配置。</p> : null}{error ? <p className="service-action-error">无法读取或写入供应商配置: {error}</p> : null}{data?.providers.length === 0 ? <p className="empty-state">尚未配置供应商。</p> : null}<div className="provider-list">{data?.providers.map((provider) => <ProviderCard key={provider.id} provider={provider} refresh={refresh} revision={data.config_revision} />)}</div></section>;
}
